baseurl = "https://superdanieldu.github.io/"
title = "SuperDaniel's Zone"
languageCode = "en-us"
disqusShortname = "SuperDanielove"
copyright = "Copyright (c) 2008 - 2019, Steve Francia; all rights reserved."
MetaDataFormat = "toml"
googleAnalytics = "UA-154851123-1"
[author]
    name = "Daniel Du"

